# Producing Plot 2
library(dplyr)
data <- read.table("exdata_data_household_power_consumption/household_power_consumption.txt", sep = ";", header = TRUE,)
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data$Date <- as.Date(data$Date, format = "%Y-%m-%d")
names(data) <- gsub("_"," ", names(data))
final_data$`Global active power` <- as.numeric(final_data$`Global active power`)
final_data <- data %>% filter(Date == "2007-02-01"| Date == "2007-02-02")
png("plot2.png", width = 480, height = 480)
final_data$DateTime <- as.POSIXct(paste(final_data$Date, final_data$Time), format = "%Y-%m-%d %H:%M:%S")
days_to_show <- as.POSIXct(seq(as.Date("2007-02-01"), as.Date("2007-02-03"), by = "day"))
xlabel <- format(days_to_show, "%a")
plot(final_data$DateTime, final_data$`Global active power`, type = "l", xaxt = "n", xlim =  range(days_to_show), ylab = "Global Active Power (kilowatts)", xlab = "")
axis(1, at = days_to_show, labels = xlabel)
dev.off()
